### ISSUE TITLE
error with experience library

### ISSUE THREAD

**Issue by balmas** [alpheios-project/safari-app-front#1]
the experience library references the browser object. We need to abstract this but for now, since we have disabled use of the experience monitor in the chrome/ff webextension we can disable it here too

**Comment by irina060981** [comment]
Done - I have removed experence track objects.
I am sorry - I have forgotten to make it using PR.
I was struggling with uploading it to safari back and with strange errors in XCode and missed the PR workflow.

P.S. I have faced with a strange crashing error - Unable to load Info.plist ...
And only one thing helps:
1) to clear all build data (using Product menu) separately for Application and Safari Extension
2) to rebuild

**Comment by balmas** [comment]
Thanks! I had a problem with Xcode yesterday too. It seemed that it had hardcoded in the project file the path to the BackgroundProcess.swift file to the full path on your machine, so it couldn't see it on mine. I solved it by deleting the file from the project and adding it back.

**Comment by irina060981** [comment]
Oh, it is interesting ... When I woked on the project I made some rearrangement  and may be I have moved some files between folders in the Xproject. I know that files on the disk and files in the XProject window are not the same, and Xproject has some mechanism to attach to each other that are not so simple.
I will be more attentive to it :) Thank you for the infoemation!
